local set = vim.opt

set.nu=true
set.hlsearch=false
set.incsearch=true
set.relativenumber=true
set.hidden=true
set.errorbells=false
set.expandtab=true
set.smartindent=true
set.wrap=false
set.swapfile=false
set.backup=false
set.undofile=true
set.incsearch=true
set.termguicolors=true
set.showmode=false
set.showmatch=true 
set.ruler=true 
set.smarttab=true
set.shiftwidth=2
set.tabstop=2
