k9s:
  cluster: kind-rdp
  namespace:
    active: data-fabric
    lockFavorites: false
    favorites:
      - all
      - data-fabric
      - default
  view:
    active: v1/pods
  featureGates:
    nodeShell: false
  proxy: null
