k9s:
  cluster: raft-aks-staging-new
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: contexts
  featureGates:
    nodeShell: false
  proxy: null
